#! /usr/bin/env python
# encoding: utf-8

def build(bld):
    bld.stlib(
        features='cxx',
        source=['src/gmock-all.cc'],
        target='gmock' if bld.variant == 'release' else 'gmockd',
        includes=['.', 'include', '../googletest/include'],
        export_includes=['include'],
        use='gtest')
