#!/usr/bin/env python
# encoding: utf-8

def build(bld):
    bld.stlib(
        features='cxx',
        source=['src/gtest-all.cc'],
        target='gtest' if bld.variant == 'release' else 'gtestd',
        includes=['.', 'include'],
        install_path='lib',
        export_includes=['include'])
